version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100;9229:9229"

# packages: []

command:
  build:
    - sudo chmod 777 -R /var/www/html
    - npm install



  dev:
    - killall webpack ||  echo "no job"
    - "D:webpack serve"

  killall:
    killall jekyll
